## Baseline images ##
services:
  ubuntu22.04:
    image: "local/cccl-ubuntu22.04"
    tty: true
    profiles: ["base"]
    build:
      cache_from:
        - "local/cccl-ubuntu22.04:latest"
        - "local/cccl-ubuntu22.04:cached"
      context: .
      dockerfile: ubuntu.base.Dockerfile
      target: devenv
      args: &ubuntu22-args
        BUILDKIT_INLINE_CACHE: "1"
        ROOT_IMAGE: "nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu22.04"
        COMPILERS: "g++-11 g++-12 clang-11 clang-12 clang-13 clang-14 clang-15"
    deploy: &deploy-template
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ubuntu20.04:
    image: "local/cccl-ubuntu20.04"
    tty: true
    profiles: ["base"]
    build:
      cache_from:
        - "local/cccl-ubuntu20.04:latest"
        - "local/cccl-ubuntu20.04:cached"
      context: .
      dockerfile: ubuntu.base.Dockerfile
      target: devenv
      args: &ubuntu20-args
        BUILDKIT_INLINE_CACHE: "1"
        ROOT_IMAGE: "nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu20.04"
        COMPILERS: "g++-8 g++-9 g++-10 clang-8 clang-9 clang-10"
    deploy: *deploy-template

  ubuntu18.04:
    image: "local/cccl-ubuntu18.04"
    tty: true
    profiles: ["base"]
    build:
      cache_from:
        - "local/cccl-ubuntu18.04:latest"
        - "local/cccl-ubuntu18.04:cached"
      context: .
      dockerfile: ubuntu.base.Dockerfile
      target: devenv
      args: &ubuntu18-args
        BUILDKIT_INLINE_CACHE: "1"
        ROOT_IMAGE: "nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu18.04"
        COMPILERS: "g++-5 g++-6 g++-7 clang-7"
    deploy: *deploy-template

##### Not used yet
##  nvhpc-ubuntu22.04:
##    image: "local/cccl-nvhpc-ubuntu22.04"
##    tty: true
##    profiles: ["base"]
##    build:
##      context: .
##      dockerfile: ubuntu.base.Dockerfile
##      target: devenv
##      args:
##        ROOT_IMAGE: "nvcr.io/nvidia/nvhpc:22.7-devel-cuda11.7-ubuntu22.04"
##    deploy: *deploy-template

## Configured images ##
### Ubuntu 22.04 images:

  gcc-11:
    extends:
      service: ubuntu22.04
    image: "libcudacxx/gcc-11"
    container_name: gcc-11
    profiles: ["gcc-11"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-11"

  gcc-12:
    extends:
      service: ubuntu22.04
    image: "libcudacxx/gcc-12"
    container_name: gcc-12
    profiles: ["gcc-12"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-12"

  clang-11:
    extends:
      service: ubuntu22.04
    image: "libcudacxx/clang-11"
    container_name: clang-11
    profiles: ["clang-11"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-11"

  clang-12:
    extends:
      service: ubuntu22.04
    image: "libcudacxx/clang-12"
    container_name: clang-12
    profiles: ["clang-12"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-12"

  clang-13:
    extends:
      service: ubuntu22.04
    image: "libcudacxx/clang-13"
    container_name: clang-13
    profiles: ["clang-13"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-13"

  clang-14:
    extends:
      service: ubuntu22.04
    image: "libcudacxx/clang-14"
    container_name: clang-14
    profiles: ["clang-14"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-14"

  clang-15:
    extends:
      service: ubuntu22.04
    image: "libcudacxx/clang-15"
    container_name: clang-15
    profiles: ["clang-15"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-15"

### Ubuntu 20.04 images:

  gcc-8:
    extends:
      service: ubuntu20.04
    image: "libcudacxx/gcc-8"
    container_name: gcc-8
    profiles: ["gcc-8"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-8"

  gcc-9:
    extends:
      service: ubuntu20.04
    image: "libcudacxx/gcc-9"
    container_name: gcc-9
    profiles: ["gcc-9"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-9"

  gcc-10:
    extends:
      service: ubuntu20.04
    image: "libcudacxx/gcc-10"
    container_name: gcc-10
    profiles: ["gcc-10"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-10"

  clang-8:
    extends:
      service: ubuntu20.04
    image: "libcudacxx/clang-8"
    container_name: clang-8
    profiles: ["clang-8"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-8"

  clang-9:
    extends:
      service: ubuntu20.04
    image: "libcudacxx/clang-9"
    container_name: clang-9
    profiles: ["clang-9"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-9"

  clang-10:
    extends:
      service: ubuntu20.04
    image: "libcudacxx/clang-10"
    container_name: clang-10
    profiles: ["clang-10"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-10"


### Ubuntu 18.04 images:

  gcc-5:
    extends:
      service: ubuntu18.04
    image: "libcudacxx/gcc-5"
    container_name: gcc-5
    profiles: ["gcc-5"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-5"

  gcc-6:
    extends:
      service: ubuntu18.04
    image: "libcudacxx/gcc-6"
    container_name: gcc-6
    profiles: ["gcc-6"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-6"

  gcc-7:
    extends:
      service: ubuntu18.04
    image: "libcudacxx/gcc-7"
    container_name: gcc-7
    profiles: ["gcc-7"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "g++-7"

  clang-7:
    extends:
      service: ubuntu18.04
    image: "libcudacxx/clang-7"
    container_name: clang-7
    profiles: ["clang-7"]
    build:
      context: ../../../
      dockerfile: environments/linux/docker/ubuntu.base.Dockerfile
      target: libcudacxx-configured
      args:
        HOST_CXX: "clang++-7"
